services:
  api:
    image: ghcr.io/jianming2024/message-server:staging
    container_name: message-api
    ports:
      - "5005:5005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - Database__PSqlConnectionString=Host=db;Port=5432;Database=Incident_Tracker;Username=postgres;Password=postgres
      - Database__RedisConnectionString=redis:6379
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  client:
    image: ghcr.io/jianming2024/message-client:staging
    container_name: message-client
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: livechat-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Incident_Tracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: message-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pgdata: